//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluffNStuff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordertable
    {
        public int o_id { get; set; }
        public Nullable<int> o_fk_subcat { get; set; }
        public Nullable<int> o_fk_user { get; set; }
        public Nullable<int> o_fk_invoice { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public Nullable<int> o_qty { get; set; }
        public Nullable<double> o_bill { get; set; }
        public Nullable<int> o_unitprice { get; set; }
    
        public virtual invoicetable invoicetable { get; set; }
        public virtual sub_category sub_category { get; set; }
        public virtual usertable usertable { get; set; }
    }
}
