//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluffNStuff.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sub_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sub_category()
        {
            this.invoicetables = new HashSet<invoicetable>();
            this.ordertables = new HashSet<ordertable>();
        }
    
        public int subcat_id { get; set; }
        public string subcat_name { get; set; }
        public string subcat_image { get; set; }
        public Nullable<int> subcat_price { get; set; }
        public string subcat_desc { get; set; }
        public Nullable<int> admin_id_fk { get; set; }
        public Nullable<int> subcat_user_id_fk { get; set; }
        public Nullable<int> cat_id_fk { get; set; }
    
        public virtual admintable admintable { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoicetable> invoicetables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordertable> ordertables { get; set; }
        public virtual usertable usertable { get; set; }
    }
}
